#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /sbin/e2fsck ]; then
	echo "e2fsck is missing. Please install the 'e2fsprogs' package."
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions
copy_exec /sbin/e2fsck

